version: '3.8'

services:
    web-server:
        container_name: web-server-fiber
        image: web-server-fiber
        ports:
            - '8080:8080'
        env_file:
            - .env
        depends_on:
            - postgres
        networks:
            - web-network
        restart: unless-stopped
    postgres:
        image: postgres:17
        container_name: postgres-pos-system
        environment:
            POSTGRES_DB: database-pos-system
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        restart: unless-stopped
        networks:
            - web-network
    pgadmin:
        image: dpage/pgadmin4:9.1
        container_name: pgadmin-pos-system
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'
        depends_on:
            - postgres
        restart: unless-stopped
        networks:
            - web-network

networks:
    web-network:
        driver: bridge

volumes:
    postgres_data:
